/**
 * Traducción entre la forma del API (snake_case, como Python) y la que usa la
 * interfaz (camelCase). Vive en un solo sitio para que cambiar el contrato del
 * backend no obligue a tocar todos los componentes.
 */

export const receptorDesdeApi = (registro) => ({
  id: registro.id,
  tipoIdentificacion: registro.tipo_identificacion,
  identificacion: registro.identificacion,
  razonSocial: registro.razon_social,
  nombreComercial: registro.nombre_comercial ?? '',
  tipoPersona: registro.tipo_persona,
  rol: registro.rol,
  correo: registro.correo ?? '',
  correo2: registro.correo2 ?? '',
  telefono1: registro.telefono1 ?? '',
  telefono2: registro.telefono2 ?? '',
  direccion: registro.direccion,
  provincia: registro.provincia ?? '',
  canton: registro.canton ?? '',
  metodoCancelacion: registro.metodo_cancelacion ?? 'Contado',
  vendedor: registro.vendedor ?? 'Sin asignar',
  listaPrecio: registro.lista_precio ?? 'PVP 1',
  zona: registro.zona ?? 'Sin zona',
  descuento: String(registro.descuento ?? '0'),
  creditoMaximo: String(registro.credito_maximo ?? '0'),
  estado: registro.estado,
});

export const receptorHaciaApi = (receptor) => ({
  tipo_identificacion: receptor.tipoIdentificacion,
  identificacion: receptor.identificacion,
  razon_social: receptor.razonSocial,
  nombre_comercial: receptor.nombreComercial || null,
  tipo_persona: receptor.tipoPersona,
  rol: receptor.rol,
  correo: receptor.correo || null,
  correo2: receptor.correo2 || null,
  telefono1: receptor.telefono1 || null,
  telefono2: receptor.telefono2 || null,
  direccion: receptor.direccion,
  provincia: receptor.provincia || null,
  canton: receptor.canton || null,
  metodo_cancelacion: receptor.metodoCancelacion,
  vendedor: receptor.vendedor || null,
  lista_precio: receptor.listaPrecio,
  zona: receptor.zona || null,
  descuento: receptor.descuento || '0',
  credito_maximo: receptor.creditoMaximo || '0',
  estado: receptor.estado ?? 'Activo',
});

export const articuloDesdeApi = (registro) => ({
  id: registro.id,
  codigo: registro.codigo,
  codigoAuxiliar: registro.codigo_auxiliar ?? '',
  nombre: registro.nombre,
  detalle: registro.detalle ?? '',
  tipo: registro.tipo,
  categoria: registro.categoria ?? 'Sin categoría',
  marca: registro.marca ?? '',
  unidad: registro.unidad,
  bodega: registro.bodega ?? 'Bodega Principal',
  ubicacion: registro.ubicacion ?? '',
  precio: Number(registro.precio),
  costo: Number(registro.costo),
  stock: registro.stock === null ? null : Number(registro.stock),
  stockMinimo: String(registro.stock_minimo ?? '0'),
  puntoReorden: String(registro.punto_reorden ?? '0'),
  stockMaximo: String(registro.stock_maximo ?? '0'),
  codigoIva: registro.codigo_iva,
  codigoIce: registro.codigo_ice ?? '',
  estado: registro.estado,
});

export const articuloHaciaApi = (articulo) => ({
  codigo: articulo.codigo,
  codigo_auxiliar: articulo.codigoAuxiliar || null,
  nombre: articulo.nombre,
  detalle: articulo.detalle || null,
  tipo: articulo.tipo,
  categoria: articulo.categoria || null,
  marca: articulo.marca || null,
  unidad: articulo.unidad,
  bodega: articulo.bodega || null,
  ubicacion: articulo.ubicacion || null,
  codigo_iva: articulo.codigoIva,
  codigo_ice: articulo.codigoIce || null,
  costo: articulo.costo || '0',
  precio: articulo.precio || '0',
  stock: articulo.stock ?? null,
  stock_minimo: articulo.stockMinimo || '0',
  punto_reorden: articulo.puntoReorden || '0',
  stock_maximo: articulo.stockMaximo || '0',
  estado: articulo.estado ?? 'Activo',
});

export const comprobanteDesdeApi = (registro) => ({
  id: registro.id,
  numero: registro.numero,
  tipo: registro.tipo,
  cliente: registro.receptor_razon_social,
  identificacion: registro.receptor_identificacion,
  fecha: registro.fecha_emision,
  total: Number(registro.importe_total),
  metodo: registro.metodo,
  estadoSRI: registro.estado_sri,
  estadoPago: registro.estado_pago,
  claveAcceso: registro.clave_acceso,
  numeroAutorizacion: registro.numero_autorizacion,
});
